### ISSUE TITLE
error in process sentinel: Symbol's value as variable is void: pfuture-buffer

### ISSUE THREAD

**Issue by lukertty** [Alexander-Miller/pfuture#4]
To reproduce:

1. emacs -Q
2. paste these to scratch
3. call M-x `eval-buffer'

```elisp
(setq package-user-dir (expand-file-name (concat "elpa-" emacs-version) user-emacs-directory))
(package-initialize)

(defun success-callback (process status output)
  (message "Success!")
  (message "Process: %s" process)
  (message "Status: %s" status)
  (message "Output: %s" output))
(defun error-callback (process status output)
  (message "Error!")
  (message "Process: %s" process)
  (message "Status: %s" status)
  (message "Output: %s" output))
(require 'pfuture)
(pfuture-callback
    ["git" "status" "--porcelain" "--ignored" "."]
  :directory "~/.emacs.d"
  :name "Pfuture"
  :connection-type 'pipe
  :on-success #'success-callback
  :on-error #'error-callback
  :on-status-change
  (message "Debug status change: %s" status))
```

Version:
* pfuture-20180908.1104
* GNU Emacs 26.1 (build 1, x86_64-apple-darwin16.7.0, Carbon Version 157 AppKit 1504.83) of 2018-09-12

Any ideas?

Thank you!

**Comment by Alexander-Miller** [comment]
Two things:
 * You need lexical scope, or it won't work.
 * The api's changed. The feature's not quite done, hence the wrong documentation in the readme, the eldoc should be all correct. Instead of the output you get the buffer where the output is collected. I've added `pfuture-output-from-buffer` to quickly grab the output with the lastest patch.

**Comment by lukertty** [comment]
It works, thank you!!
